import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * Merge Tailwind classes intelligently — `clsx` handles conditional class lists
 * and `twMerge` resolves Tailwind class conflicts (e.g. `px-2 px-4` → `px-4`).
 * Every shadcn/ui component generated by the CLI imports this `cn` helper.
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
